# Generated by Django 4.1.1 on 2022-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products'),
        ),
    ]
