# Generated by Django 4.1.1 on 2022-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProduct', '0002_alter_product_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
